id: PDF4FD415
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: bo
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    786ea7c07ee34900af1e2c601bab00de:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    8b6a1be29f08473697d6f3fe205e0f16:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    11aa5ec89dde4aa9a1f14f3be7cfb90d:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    5d8f0318af724dfa8904e43b8b2ce3a5:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    291b88fe0e5d4b588c0f0c28bc4781d1:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    f821a162d62a4eeda0d76b542a84e7e4:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    9d7d10bbaa144236ae7c03daac8df151:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    74729e42cded42a8ba7b44b982604b25:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    ff31264e24ad4685a5b8de027f1c8cb5:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    5cf1e31e77c34bf5b8de8a1ea04ecc43:
      title: The Lament of Rudra
      parent: Confession
    de41b235c6e345a7924ecd5f27f8e177:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    067e8d4b4347472c8f09379771d93c0a:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    39c6c2b14bfb4b57971de26ec30a4da5:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    0ab228fc140a4499960d5e2b52f00679:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    3d0b904a84954c839f951fe30a08da53:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    1a85642370be4e308c8b0ac994fd52c6:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    e0410f38d4b14250b6e30e44703ce26d:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    f20970c72e914756976f870b3dbf8aa5:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    9124a30d5abc4e4e8bd25016ae62fc0d:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    e7c0d0e79b194274b9f2d48bd7772f33:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    57836c386925488f978ff543db250c7c:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    1304e36be01c4a08834ba4635b6ff2f7:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    99b3454642ff4e71b01b3c686259f796:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    75370631f1e54a43bfd60a3c10198f56:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    debac2c91183444ea55b9feec55eaedc:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    1e807f1ff9964ba1951c985c1ddfbc16:
      title: The Twenty-Eight Commitments
      parent: Tantra
    99e2f415666c4a34b2fb311b00d36de8:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.948485'
last_modified_at: '2022-02-28T22:46:47.948488'
